improving_docs
adafruit/Adafruit_CircuitPython_BNO08x pull request #23
Opened 2021-04-26 12:59 UTC by jposada202020

@dhalbert This one is a little different, I would like some feedback on how to deal with the different speed in the buses. I have not change yet the busio reference waiting for your feedback, however all the rest is done. If you could guide me, there is also the BNO08x_RVC that is setup in the same way, 

Thanks,

2021-04-26 14:34 UTC, dhalbert requested changes
I did some more copy-editing. My impression is that 400kHz is not required, but it can run at the higher speed, so I added a comment to that effect.

2021-04-26 14:34 UTC, dhalbert commented on adafruit_bno08x/i2c.py
> +    :param ~digitalio.DigitalInOut reset: The pin object to reset
```suggestion
    :param ~digitalio.DigitalInOut reset: Optional for I2C use. Connected to the RST pin; used to hard-reset the device.
```

2021-04-26 14:34 UTC, dhalbert commented on examples/bno08x_simpletest_spi.py
>  # need to limit clock to 3Mhz
```suggestion
# need to limit clock to 3MHz
```

2021-04-26 14:34 UTC, dhalbert commented on adafruit_bno08x/spi.py
> +    :param ~digitalio.DigitalInOut resetpin: The pin object to reset
```suggestion
    :param ~digitalio.DigitalInOut resetpin: Required for SPI mode. Connected to the RST pin on the device, and used to hard-reset the device.
```

2021-04-26 14:34 UTC, dhalbert commented on adafruit_bno08x/__init__.py
> +    This sensor could use three different communication buses:
```suggestion
    This sensor is able to communicate over I2C, SPI, or UART:
```

2021-04-26 14:34 UTC, dhalbert commented on adafruit_bno08x/i2c.py
> +            i2c = busio.I2C(board.SCL, board.SDA, frequency=400000)
```suggestion
           # The sensor can communicate over I2C at 400kHz if you need the higher speed.
            i2c = busio.I2C(board.SCL, board.SDA, frequency=400000)
```

2021-04-26 18:37 UTC, dherrada commented
Nice job getting the docs to build!

2021-05-12 16:29 UTC, jposada202020 commented
Danh let me know if you have any other comments, gladly to work on that, if `None` I think that we could make the changes. Thanks

2021-05-25 18:10 UTC, dhalbert approved these changes
Sorry - this fell off my list. Looks good!

2021-05-25 18:10 UTC, merged

2021-06-07 15:32 UTC, dherrada commented
@jposada202020 Do you think you could reopen this branch and make another PR? I messed something up with moving to main and this PR wasn't included in the main branch.

2021-06-07 15:38 UTC, jposada202020 commented
@dherrada No problem I could that tonight. Just to clarify, I need to resubmit PR? to main, is that correct? just to be sure and apply the same for all the others :) thanks

2021-06-07 16:16 UTC, dherrada commented
@jposada202020 Yep. Luckily the mistake that I made seems to not have affected many libraries, but 2 or 3 PRs you made were affected and I've pinged you in all of them. I'm not really sure how late you can reopen a branch or if you have it saved locally, so let me know if you've got questions.

2021-06-07 16:48 UTC, jposada202020 commented
@dherrada Ok, Understood, depends on how often I work in the library, I have or have not the branch. But I will figure it out. And make the changes accordingly.

2021-06-07 16:53 UTC, dherrada commented
@jposada202020 Sounds good.